config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'

  # check email uniqueness in js whenever keypress
  post "/check_email" => "home#check_email"

  # mypouch
  get 'mypouch/index' => "mypouch#index"
  get 'mypouch/face'=> "mypouch#face"
  post 'mypouch/survey' => "mypouch#survey"
  get 'mypouch/survey' => "mypouch#survey"
  post 'mypouch/keyword'=> "mypouch#keyword"
  get 'mypouch/keyword'=> "mypouch#face"
  post 'mypouch/result' => "mypouch#result"
  get 'mypouch/result' => "home#index"

  # contents
  resources :contents do
    resources :comments
    member do
      put "like", to: "contents#upvote"
    end
  end
  get "/contents/custom/:category" => "contents#custom"
  get "/contents/filter/:filter" => "contents#filter"

  # products
  resources :products do
    resources :reviews
  end
  get "/products/custom/:category" => "products#custom"
  get "/products/filter/:filter" => "products#filter"

  # ranking
  get '/ranking/category/:category' => "ranking#category"

  # store
  get '/store/index'
  get '/store/category/:category' => "store#category"
  get '/store/filter/:filter' => "store#filter"

  # creatures
  resources :creatures do
    resources :talks
    member do
      put "like", to: "creatures#upvote"
    end
  end
  get 'creatures/category/:category' => "creatures#category"

  # Admin
  get 'admin/index' => "admin#index"
  get 'admin/userinfo' => "admin#userinfo"
  get 'admin/contentinfo' => "admin#contentinfo"
  get 'admin/productinfo' => "admin#productinfo"
  get 'admin/creatureinfo' => "admin#creatureinfo"

  # tinymce
  post '/tinymce_assets' => 'tinymce_assets#create'



end

app/models/content.rb
class Content < ApplicationRecord
  # validation
  validates :title, :presence => true
  validates :subtitle, :presence => true
  validates :body, :presence => true
  validates :category, :presence => true

  has_and_belongs_to_many :tags
  mount_uploader :thumb, ImageUploader # carrierwave
  has_many :comments, :dependent => :delete_all
  belongs_to :user
  acts_as_votable
  is_impressionable
  resourcify
  has_and_belongs_to_many :products

  after_create do
    content = Content.find_by(id: self.id)
    hashtags = self.keyword.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      content.tags << tag
    end
  end

  before_update do
    content = Content.find_by(id: self.id)
    content.tags.clear
    hashtags = self.keyword.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      content.tags << tag
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy, :upvote]
  # before_action :authenticate_user!, only: [:new, :edit, :delete, :upvote, :custom]
  impressionist actions: [:show]
  # load_and_authorize_resource

  # 전역변수 초기화
  @@filter = ""

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
    @tags = @content.tags
    @products = @content.products
  end

  # GET /contents/new
  def new
    @content = current_user.contents.build
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = current_user.contents.build(content_params)
    alpha = ['a', 'b', 'c', 'd', 'e']

    respond_to do |format|
      if @content.save
        for i in 0..4
          if params["#{alpha[i]}"] != ""
            product = Product.find_by_id(params["#{alpha[i]}"].to_i)
            @content.products << product
          end
        end
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # 맞춤 콘텐츠
  def custom
    @@category = params[:category]
    if @@category == "all"
      @contents = Content.all
      # 맞춤 알고리즘
      personalize(@contents)
    else
      if @@category == "skincare"
        @cate_ko = "스킨케어"
      elsif @@category == "faceup"
        @cate_ko = "페이스업"
      elsif @@category == "hair"
        @cate_ko = "헤어"
      else
        @cate_ko = "바디"
      end
      @contents = Content.where(:category => @cate_ko)
      # 맞춤 알고리즘
      personalize(@contents)
    end

    @contents_filter = Content.all
    if @@filter != ""
      if @@filter == "latest"
        @contents_normal = @contents_filter.order("created_at DESC")
      elsif @@filter == "hottest"
        hottest(@contents_filter)
      end
    else
      @contents_normal = @contents_filter.order("created_at DESC")
    end
  end

  def filter
    @@filter = params[:filter]
    redirect_to "/contents/custom/#{@@category}"
  end

  # acts_as_votable
  # 투표 관련 Controller 내용 : 찬성
  def upvote
    @content = Content.find(params[:id])

    @content.upvote_by current_user
    redirect_to(request.referer)
    # redirect_to(request.referrer, :notice => '해당 글을 추천하셨습니다.')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:thumb, :title, :subtitle, :body, :link, :category, :keyword,
                                      :normal, :dry, :oily, :complex, :sensitive,
                                      :notcare, :basecare, :hardcare, :makeup, :idol)
    end

    # filter
    def hottest(contents)
      @contentsArray = Array.new(contents.count){Array.new(2)}
      index = 0

      contents.each do |content|
        @contentsArray[index][1] = content.id

        # 만약 좋아요가 없을 경우 0을 입력
        if content.get_upvotes.size == nil
          @contentsArray[index][0] = 0
        else
          @contentsArray[index][0] = content.get_upvotes.size
        end
        index += 1
      end
      @contentsArray = @contentsArray.sort.reverse

      @contents_normal = []
      for i in 0..(@contentsArray.length-1)
        @contents_normal << Content.find(@contentsArray[i][1])
      end
    end

    # personalize_contents
    def personalize(contents)
      @contentsArray = Array.new(contents.count){Array.new(2)}
      index = 0
      skintype = ""

      @user = current_user
      if @user.skintype == "건성"
        skintype = "dry"
      elsif @user.skintype == "일반"
        skintype = "normal"
      elsif @user.skintype == "지성"
        skintype = "oily"
      elsif @user.skintype == "복합성"
        skintype = "complex"
      elsif @user.skintype == "민감성"
        skintype = "sensitive"
      end

      contents.each do |content|
        @contentsArray[index][1] = content.id
        @contentsArray[index][0] = 0

        u_tags = @user.tags
        c_tags = content.tags

        c_tags.each do |c_tag|
          if u_tags.include?(c_tag)
            @contentsArray[index][0] += 1
          end
        end

        index += 1
      end

      @contentsArray = @contentsArray.sort.reverse

      @contents = []
      for i in 1..(@contentsArray.count-1)
        content = Content.find_by_id(@contentsArray[i][1])
        if content[skintype] == true
          @contents << content
        end
      end

      if @contents.count >= 12
        @contents = @contents[0..11]
      end
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for(content) do |f| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :thumb %>
    <%= f.file_field :thumb, accept: 'image/png image/gif image/jpg' %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= tinymce :language => "ko" %>
    <%= f.text_area :body, id: :content_body, class: "form-control tinymce", rows: "10" %>

  </div>
  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :category %>
    <%= f.select(:category, ['스킨케어', '페이스업', '헤어', '바디'] , {}, { :class => ''}) %>
  </div>
  <div class="field">
    <%= f.label :keyword %>
    <%= f.text_field :keyword %>
  </div>

  <div class="field">
    <%= f.label :normal %>
    <%= f.radio_button :normal, true %>
    <%= f.label :normal, 'yes' %>
    <%= f.radio_button :normal, false %>
    <%= f.label :normal, 'no' %>
  </div>
  <div class="field">
    <%= f.label :dry %>
    <%= f.radio_button :dry, true %>
    <%= f.label :dry, 'yes' %>
    <%= f.radio_button :dry, false %>
    <%= f.label :dry, 'no' %>
  </div>
  <div class="field">
    <%= f.label :oily %>
    <%= f.radio_button :oily, true %>
    <%= f.label :oily, 'yes' %>
    <%= f.radio_button :oily, false %>
    <%= f.label :oily, 'no' %>
  </div>
  <div class="field">
    <%= f.label :complex %>
    <%= f.radio_button :complex, true %>
    <%= f.label :complex, 'yes' %>
    <%= f.radio_button :complex, false %>
    <%= f.label :complex, 'no' %>
  </div>
  <div class="field">
    <%= f.label :sensitive%>
    <%= f.radio_button :sensitive, true %>
    <%= f.label :sensitive, 'yes' %>
    <%= f.radio_button :sensitive, false %>
    <%= f.label :sensitive, 'no' %>
  </div>

  <div class="field">
    <%= f.label :notcare %>
    <%= f.radio_button :notcare, true %>
    <%= f.label :notcare, 'yes' %>
    <%= f.radio_button :notcare, false %>
    <%= f.label :notcare, 'no' %>
  </div>
  <div class="field">
    <%= f.label :basecare %>
    <%= f.radio_button :basecare, true %>
    <%= f.label :basecare, 'yes' %>
    <%= f.radio_button :basecare, false %>
    <%= f.label :basecare, 'no' %>
  </div>
  <div class="field">
    <%= f.label :hardcare %>
    <%= f.radio_button :hardcare, true %>
    <%= f.label :hardcare, 'yes' %>
    <%= f.radio_button :hardcare, false %>
    <%= f.label :hardcare, 'no' %>
  </div>
  <div class="fielhardcared">
    <%= f.label :makeup %>
    <%= f.radio_button :makeup, true %>
    <%= f.label :makeup, 'yes' %>
    <%= f.radio_button :makeup, false %>
    <%= f.label :makeup, 'no' %>
  </div>
  <div class="field">
    <%= f.label :idol %>
    <%= f.radio_button :idol, true %>
    <%= f.label :idol, 'yes' %>
    <%= f.radio_button :idol, false %>
    <%= f.label :idol, 'no' %>
  </div>
  <hr>

  <div class="field">
    <h3>관련된 제품 ID를 입력하세요.</h3>
    <input type="number" name="a">
    <input type="number" name="b">
    <input type="number" name="c">
    <input type="number" name="d">
    <input type="number" name="e">
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/custom.html.erb
<nav class="m_sub_title">
  <ul>
    <li><a class="m_m1" href="/contents/custom/<%= 'all' %>">ALL</a></li>
    <li><a class="m_m2" href="/contents/custom/<%= 'skincare' %>">스킨케어</a></li>
    <li><a class="m_m3" href="/contents/custom/<%= 'faceup' %>">페이스업</a></li>
    <li><a class="m_m4" href="/contents/custom/<%= 'hair' %>">헤어</a></li>
    <li><a class="m_m5" href="/contents/custom/<%= 'body' %>">바디</a></li>
  </ul>
</nav>
<nav class="m_sub_title_blank"></nav>

<article class="custom">
  <section>
    <div class="content_main1">
      <div class="i1">
        <div class="in1">맞춤</div>
        <div class="in2"><%= current_user.nickname %>님을 위한 맞춤 매뉴얼</div>
      </div>

      <div class="line"></div>
      
      <div class="i2">
        <div class="in1">태그</div>
        
        <div class="in2">
          <% if current_user.keyword != nil %>
            <% tags = current_user.tags %>
            <% tags.each do |tag| %>
              <span>#<%= tag.name %></span>&nbsp
            <% end %>
          <% else %>
            <p>피부특성 분석을 진행해 보세요! <a href="/mypouch/face">바로가기</a></p>
          <% end %>
        </div>
      </div>
    </div>
  </section>

  <% if current_user.skintype != nil %>
    <section class="trend">
      <% @contents.each do |content| %>
        <div>
          <div class="ct_thumb">
            <div class="ct_title_cat"><%= content.category%></div>
            <%= link_to image_tag(content.thumb.main), content_path(content) %><!-- 썸네일 이미지 -->
            <div class="ct_title_likes"><div class="ico_heart_w"></div><%= link_to "#{content.get_upvotes.size}", like_content_path(content), method: :put %></div>
            
          </div>

          <div class="ct_title">
             <%= content.title %><!-- 타이틀이 노출됩니다. -->
          </div>

          <!--
          <div class="ct_likes">
            <span>Views <%= content.impressionist_count %></span>
          </div>
          -->

          <div class="ct_keyword">
            <p>
              <% tags = content.tags %>
              <% tags.each do |tag| %><!--키워드 전체가 노출됩니. -->
                <span>#<%= tag.name %></span>&nbsp
              <% end %>
            </p>
          </div>
        </div>
      <% end %>
    </section>
  <% end %>
</article>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contents</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.title %></td>
        <td><%= link_to 'Show', content %></td>
        <td><%= link_to 'Edit', edit_content_path(content) %></td>
        <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<article>
  <p id="notice"><%= notice %></p>

    <div class="con_tag">
      <% @tags.each do |tag| %>
      <span>#<%= tag.name %></span>&nbsp
      <% end %>
    </div>

    <div class="con_thumb" >

      <div class="con thumb1">
        <img src="<%= @content.thumb.detail %>" alt="" />
      </div>

      <div class="con thumb2">
        <div class="con_title"><%= @content.title %></div>
        <div class="con_s_title"><%= @content.subtitle %></div>
      </div>

      <div class="con thumb3">
        <div class="btn_likes"><a href="<%= like_content_path(@content) %>" data-method="put"><div class="ico_heart"></div><%= @content.get_upvotes.size %></a></div>
        <div class="btn_views"><div class="ico_views"></div> <%= @content.impressionist_count %></div>
      </div>

    </div>

    <div class="con_body">
      <%= @content.body.html_safe%>
    </div>

    <div class="btn_likes_bot"><a href="<%= like_content_path(@content) %>" data-method="put"><div class="ico_heart"></div><%= @content.get_upvotes.size %></a></div>

    <div class="">
      <% @products.each do |product| %>
        <%= product.name %>
      <% end %>
    </div>

  <%= link_to '수정', edit_content_path(@content) %> /
  <%= link_to '삭제', @content, method: :delete, data: { confirm: '정말 삭제하시겠습니까?' } %>

  <div class="comment_num">댓글 <%= @content.comments.count %>개</div>
  <div class="line"></div>

  <%= render "comments/form" %>
  <%= render @content.comments %>

</article>