config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'

  # check email uniqueness in js whenever keypress
  post "/check_email" => "home#check_email"

  # mypouch
  get 'mypouch/index' => "mypouch#index"
  get 'mypouch/face'=> "mypouch#face"
  post 'mypouch/survey' => "mypouch#survey"
  get 'mypouch/survey' => "mypouch#survey"
  post 'mypouch/keyword'=> "mypouch#keyword"
  get 'mypouch/keyword'=> "mypouch#face"
  post 'mypouch/result' => "mypouch#result"
  get 'mypouch/result' => "home#index"

  # contents
  resources :contents do
    resources :comments
    member do
      put "like", to: "contents#upvote"
    end
  end
  get "/contents/custom/:category" => "contents#custom"
  get "/contents/filter/:filter" => "contents#filter"

  # products
  resources :products do
    resources :reviews
  end
  get "/products/custom/:category" => "products#custom"
  get "/products/filter/:filter" => "products#filter"

  # ranking
  get '/ranking/category/:category' => "ranking#category"

  # store
  get '/store/index'
  get '/store/category/:category' => "store#category"
  get '/store/filter/:filter' => "store#filter"

  # creatures
  resources :creatures do
    resources :talks
    member do
      put "like", to: "creatures#upvote"
    end
  end
  get 'creatures/category/:category' => "creatures#category"

  # Admin
  get 'admin/index' => "admin#index"
  get 'admin/userinfo' => "admin#userinfo"
  get 'admin/contentinfo' => "admin#contentinfo"
  get 'admin/productinfo' => "admin#productinfo"
  get 'admin/creatureinfo' => "admin#creatureinfo"

  # tinymce
  post '/tinymce_assets' => 'tinymce_assets#create'



end

app/controllers/mypouch_controller.rb
require "google/cloud/vision"
require "rmagick"

class MypouchController < ApplicationController
  before_action :authenticate_user!
  skip_before_filter :verify_authenticity_token, only: [:result, :survey, :keyword] # Invalid AuthenticityToken Error

  def index
    @user = User.find_by(id: current_user.id)
    @contents_all = Content.all
    @products_all = Product.all
    @contents = []
    @products = []

    # 맞춤 콘텐츠
    @contents_all.each do |content|
      if (content.category=="스킨케어") || (content.category=="페이스업")
        @contents << content
      end
    end
    @contents = @contents[0..3]

    # 맞춤 제품
    @products_all.each do |product|
      if (product.category=="스킨케어") || (product.category=="페이스업")
        @products << product
      end
    end
    @products = @products[0..3]

    # 내가 쓴 Creature
    @creatures = Creature.where(:user_id => current_user.id)
  end

  def face
    @user = User.find_by(id: current_user.id)
  end

  def survey
    @user = User.find_by(id: current_user.id)
    @message = true
    if params.key?("user")
      @user.face.store!(params[:user][:face])
      @user.face = params[:user][:face]
      @user.save

      # import vision api
      vision = Google::Cloud::Vision.new(
        project: "savvy-badge-225906",
        keyfile: "./google/key.json"
      )

      # face detect
      image = vision.image @user.face.path
      faces = image.faces

      if faces.length == 0
        @message = false
      end

      # draw line - face detect
      image = Magick::Image.read(@user.face.path).first
      faces.each do |face|
        puts "Face bounds:"
        face.bounds.face.each do |vector|
          puts "(#{vector.x}, #{vector.y})"
        end

        draw = Magick::Draw.new
        draw.stroke = "green"
        draw.stroke_width 5
        draw.fill_opacity 0

        x1 = face.bounds.face[0].x.to_i
        y1 = face.bounds.face[0].y.to_i
        x2 = face.bounds.face[2].x.to_i
        y2 = face.bounds.face[2].y.to_i

        draw.rectangle x1, y1, x2, y2
        draw.draw image

      end

      # save face-detect img
      temp_file = Tempfile.new(['temp', '.png'])
      image.write(temp_file.path)
      @user.face = temp_file
      @user.save

      # close temp
      temp_file.close
      temp_file.unlink
    elsif !params.key?("user")
      redirect_to "/mypouch/face"
    end
  end

  def keyword
    @user = User.find_by(id: current_user.id)

    @user.skintype = params[:skintype]
    @user.save
  end

  def result
    temp1 = ['aa', 'ab', 'ac', 'ad', 'ae', 'af',
             'ag', 'ah', 'ai', 'aj', 'ak', 'al',
             'am', 'an', 'ao', 'ap', 'aq', 'ar']

    temp2 = ['ba', 'bb', 'bc', 'bd', 'be', 'bf',
             'bg', 'bh' ]

    @keyword = ""

    for i in 0..(temp1.length-1)
      if params["#{temp1[i]}"] != nil
        @keyword += (params["#{temp1[i]}"].to_s + " ")
      end
    end
    for i in 0..(temp2.length-1)
      if params["#{temp2[i]}"] != nil
        @keyword += (params["#{temp2[i]}"].to_s + " ")
      end
    end

    @user = User.find_by(id: current_user.id)
    if params["usertype"] != nil
      if params["usertype"] == "notcare"
        @user.usertype = "무관심형"
      elsif params["usertype"] == "basecare"
        @user.usertype = "기초케어형"
      elsif params["usertype"] == "hardcare"
        @user.usertype = "심화케어형"
      elsif params["usertype"] == "makeup"
        @user.usertype = "적극적화장형"
      elsif params["usertype"] == "idol"
        @user.usertype = "아이돌형"
      end
    end

    # keyword 안의 각 키워드를 Tag(user.tags) 모델에 저장하기
    @user.tags.clear
    hashtags = @keyword.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      @user.tags << tag # 태그 모델 저장
    end

    # user.keyword 저장
    @user.keyword = @keyword
    @user.save
  end
end

app/helpers/mypouch_helper.rb
module MypouchHelper
end

app/views/mypouch/face.html.erb
<h1>Mypouch#face</h1>
<form action="/mypouch/survey" enctype="multipart/form-data" method="post">
  <label for="user_face">Face</label>
  <input accept="image/png image/gif image/jpg" type="file" name="user[face]" multipl="true" id="user_face">
  <input type="submit" value="Next">
</form>

app/views/mypouch/index.html.erb
<article>
  <div class="">
    <img src="<%= current_user.profile.main %>" alt="" />
    <%= @user.nickname %>`s pouch
  </div>
  <br>

  <% if @user.skintype == nil %>
    <%= link_to "나의 피부특성 분석하기", "/mypouch/face" %> <br>
    <%= link_to "Edit", edit_user_registration_path(@user) %>
  <% else %>
    <div class="">
      <div class="skintype">피부타입: <%= @user.skintype %></div>
      <div class="skintype">페이스업 정도: <%= @user.usertype %></div>
      <div class="age">연령대: <%= @user.age %></div>

      <p style="color: red">
        키워드:
        <% @user.tags.each do |tag| %>
          <span>#<%= tag.name %></span>&nbsp
        <% end %>
      </p>

      <%= link_to "다시 분석하기", "/mypouch/face" %> <br>
      <%= link_to "Edit", edit_user_registration_path(@user) %>
    </div>
  <% end %>

  <br>
</article>


<article>
  <% if @user.skintype != nil %>
    <section>
      <h3>상위 맞춤매뉴얼 4개</h3>
      <a href="/contents/custom/<%= 'all' %>"><span>+더보기</span></a>
      <% @contents.each do |content| %>
        <div class="" style="border: 1px solid #555">
          <div class="">
            <%= link_to image_tag(content.thumb.main), content_path(content) %><!-- 썸네일 이미지 -->
          </div>

          <div class="">
            <h3><span style="color:red;"><%= content.category%></span> | <%= content.title %></h3><!-- 타이틀이 노출됩니다. -->
          </div>

          <div class>
            <%= link_to "Likes #{content.get_upvotes.size}", like_content_path(content), method: :put %>
            <span>Views <%= content.impressionist_count %></span>
            <p class=""><%= time_ago_in_words(content.created_at) %> 전 [ <%= content.created_at.strftime('%Y-%m-%d %H:%M') %> ]</p>
          </div>

          <div class="">
            <p>
              <% tags = content.tags %>
              <% tags.each do |tag| %><!--키워드 전체가 노출됩니. -->
                <span>#<%= tag.name %></span>&nbsp
              <% end %>
            </p>
          </div>
        </div>
      <% end %>
    </section>
    <br>

    <section>
      <h3>상위 맞춤제품 4개</h3>
      <a href="/products/custom/<%= 'all' %>"><span>+더보기</span></a>
      <% @products.each do |product| %>
        <div class="" style="border: 1px solid #555">
          <div class="">
            <span><%= product.category %></span>
            <%= link_to image_tag(product.thumb.main), product_path(product) %><!-- 썸네일 이미지 -->
          </div>
          <div class="">
            <h3><%= product.name %>(<%= product.brand %>)</h3>
            <%
              price = product.price.to_s
              price_string = ""
              if price.length == 4
                price_string = price[0] + "," + price[1..3]
              elsif price.length == 5
                price_string = price[0..1] + "," + price[2..4]
              elsif price.length == 6
                price_string = price[0..2] + "," + price[3..5]
              end
            %>
            <h5>가격: <%= price_string %>원</h5>
          </div>
          <div class=""><%= product.score %></div>

          <div class="">
            <% tags = product.tags %>
            <% tags.each do |tag| %>
              <span>#<%= tag.name %></span>&nbsp
            <% end %>
          </div>
        </div>
      <% end %>
    </section>
    <br>
  <% end %>

  <section>
    <h3>내가 작성한 Creatures</h3>
    <% @creatures.each do |creature| %>
      <div class="" style="border: 1px solid #555">
        <div class="">
          <%= link_to image_tag(creature.thumb.main), creature_path(creature) %><!-- 썸네일 이미지 -->
        </div>

        <div class="">
          <h3><span style="color:red;"><%= creature.category%></span> | <%= creature.title %></h3><!-- 타이틀이 노출됩니다. -->
        </div>

        <div class>
          <%= link_to "Likes #{creature.get_upvotes.size}", like_creature_path(creature), method: :put %>
          <span>Views <%= creature.impressionist_count %></span>
        </div>

        <div class="">
          <p>
            <% tags = creature.tags %>
            <% tags.each do |tag| %><!--키워드 전체가 노출됩니. -->
              <span>#<%= tag.name %></span>&nbsp
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
  </section>
</article>

<article>
  <%= link_to '피부 분석 바로가기', '/mypouch/face'%>
</article>

app/views/mypouch/keyword.html.erb
<h1>Mypouch#keyword</h1>

<form action="/mypouch/result" method="post" class="user_check_keyword">
  <h3><%= @user.nickname %>님이 원하는 화장품 사용 단계를 선택해주세요.</h3>

  <input type="radio" name="usertype" value="notcare" id="usertype">
  <label for="usertype">무관심형</label>
  <input type="radio" name="usertype" value="basecare" id="usertype">
  <label for="usertype">기초케어형</label>
  <input type="radio" name="usertype" value="hardcare" id="usertype">
  <label for="usertype">심화케어형</label>
  <input type="radio" name="usertype" value="makeup" id="usertype">
  <label for="usertype">적극적화장형</label>
  <input type="radio" name="usertype" value="idol" id="usertype">
  <label for="usertype">아이돌</label>
  <br><br>

  <% temp1 = ['aa', 'ab', 'ac', 'ad', 'ae', 'af',
              'ag', 'ah', 'ai', 'aj', 'ak', 'al',
              'am', 'an', 'ao', 'ap', 'aq', 'ar'] %>
  <h3><%= @user.nickname %>님의 피부고민을 선택해주세요.</h3>
  <input type="checkbox" name="<%= temp1[0] %>" value="#주름" id="key1">
  <label for="key1">주름</label>
  <input type="checkbox" name="<%= temp1[1] %>" value="#피지" id="key2">
  <label for="key2">피지</label>
  <input type="checkbox" name="<%= temp1[2] %>" value="#잡티" id="key3">
  <label for="key3">잡티</label>
  <input type="checkbox" name="<%= temp1[3] %>" value="#넓은모공" id="key4">
  <label for="key4">넓은모공</label>
  <input type="checkbox" name="<%= temp1[4] %>" value="#피부탄력저하" id="key5">
  <label for="key5">피부탄력저하</label>
  <input type="checkbox" name="<%= temp1[5] %>" value="#아토피" id="key6">
  <label for="key6">아토피</label>

  <input type="checkbox" name="<%= temp1[6] %>" value="#여드름" id="key7">
  <label for="key7">여드름</label>
  <input type="checkbox" name="<%= temp1[7] %>" value="#건조한피부" id="key8">
  <label for="key8">건조한피부</label>
  <input type="checkbox" name="<%= temp1[8] %>" value="#뾰루지" id="key9">
  <label for="key9">뾰루지</label>
  <input type="checkbox" name="<%= temp1[9] %>" value="#각질" id="key10">
  <label for="key10">각질</label>
  <input type="checkbox" name="<%= temp1[10] %>" value="#기미" id="key11">
  <label for="key11">기미</label>
  <input type="checkbox" name="<%= temp1[11] %>" value="#다크써클" id="key12">
  <label for="key12">다크써클</label>

  <input type="checkbox" name="<%= temp1[12] %>" value="#두피여드름" id="key13">
  <label for="key13">두피여드름</label>
  <input type="checkbox" name="<%= temp1[13] %>" value="#비듬" id="key14">
  <label for="key14">비듬</label>
  <input type="checkbox" name="<%= temp1[14] %>" value="#탈모" id="key15">
  <label for="key15">탈모</label>
  <input type="checkbox" name="<%= temp1[15] %>" value="#바디여드름" id="key16">
  <label for="key16">바디여드름</label>
  <input type="checkbox" name="<%= temp1[16] %>" value="#바디각질" id="key17">
  <label for="key17">바디각질</label>
  <input type="checkbox" name="<%= temp1[17] %>" value="#바디건조" id="key18">
  <label for="key18">바디건조</label>
  <br><br>

  <% temp2 = ['ba', 'bb', 'bc', 'bd', 'be', 'bf',
              'bg', 'bh'] %>
  <h3><%= @user.nickname %>님의 관심 키워드를 선택해주세요.</h3>
  <input type="checkbox" name="<%= temp2[0] %>" value="#면접" id="key19">
  <label for="key19">면접</label>
  <input type="checkbox" name="<%= temp2[1] %>" value="#소개팅" id="key20">
  <label for="key20">소개팅</label>
  <input type="checkbox" name="<%= temp2[2] %>" value="#가벼운" id="key21">
  <label for="key21">가벼운</label>
  <input type="checkbox" name="<%= temp2[3] %>" value="#간편한" id="key22">
  <label for="key22">간편한</label>
  <input type="checkbox" name="<%= temp2[4] %>" value="#데이트" id="key23">
  <label for="key23">데이트</label>
  <input type="checkbox" name="<%= temp2[5] %>" value="#대학생" id="key24">
  <label for="key24">대학생</label>
  <input type="checkbox" name="<%= temp2[6] %>" value="#회사원" id="key25">
  <label for="key25">회사원</label>
  <input type="checkbox" name="<%= temp2[7] %>" value="#비즈니스" id="key26">
  <label for="key26">비즈니스</label>
  <br>

  <input type="submit" value="완료">
</form>

app/views/mypouch/result.html.erb
<article class="">
  <div class="">
    <h3><%= @user.nickname %>님의 <span styke="color: red">피부특성 분석</span> 결과입니다.</h3>
    <button><a href="<%= edit_user_registration_path(@user) %>"></a></button>
  </div>
  <div class="">
    <div class="">피부 타입: <%= @user.skintype %></div>
    <div class="">페이스업 정도: <%= @user.usertype %></div>
    <div class="">연령: <%= @user.age %></div>
  </div>
  <div class="">
    <p>
      <% @user.tags.each do |tag| %>
        <span>#<%= tag.name %></span>&nbsp
      <% end %>
    </p>
  </div>
</article>
<br>

<article>
  <section>
    <img src="<%= @user.face.main %>" alt="">
  </section>
  <br>

  <!-- 추후 각 피부 타입에 따른 설명을 아래 if 문 안에 넣어줄 예정 -->
  <% if @user.skintype == "건성" %>
  <% elsif @user.skintype == "일반" %>
  <% elsif @user.skintype == "지성" %>
  <% elsif @user.skintype == "복합성" %>
  <% else %>
  <% end %>

  <!-- 피부 타입에 따른 설명 예시 -->
  <section>
    <div class="">
      <h4>1. 당신의 피부는? 건조함을 달고 사는 '건성피부' 타입</h4>
      <p>
        수분과 피지가 부족해 피부 표면이 메마르고 피부 당김이 심해 거칠거칠한 타입이에요.
        모공이 섬세하기 때문에 잔주름이나 화장들뜸이 다른 피부타입에 비해 심한 편이랍니다.
      </p>
    </div>

    <div class="">
      <h4>2. 건성피부의 특징</h4>
      <p>
        수분 부족으로 인해 메마르고 거친 타입과 피지가 부족해 건조한 타입으로 나눌 수 있어요.
        세안으로 인해 수분을 지나치게 빼앗기지 않도록 해야 하며, 보습효과가 큰 크림을 사용해 피부표면 수분을 적당히 유지시켜 주어야 합니다.
      </p>
    </div>

    <div class="">
      <h4>3. 건성피부의 관리법</h4>
      <p>
        건성피부일 경우 낮과 밤을 나눠 따로 관리해주는 것이 좋아요.
        밤에는 아이메이크업을 오일 성분이 없는 리무버로 닦아내주세요. 역시나 자극 없는 세안제로 가볍게 마사지 한 후 미지근한 물로 15번 ~ 20번 세수! 씻어낸 물을 너무 말리지 않는 것이 중요하다.
      </p>
    </div>
  </section>
</article>
<%= link_to '맞춤메뉴얼/맞춤제품 확인하기', '/mypouch/index'%>

app/views/mypouch/survey.html.erb
<h1>Mypouch#survey</h1>
<% if @message == true %>
  <img src="<%= @user.face.main %>" alt="">
<% elsif @message == false %>
  정확한 얼굴사진을 다시 등록해 주세요!<br>
  <%= link_to "뒤로가기", "/mypouch/face" %>
<% end %>

<div class="s_n"></div>
<div class="s_q"></div>

<form action="/mypouch/keyword" method="post">
  <input type="hidden" id="skintype" name="skintype">
  <input type="hidden" value="관심 키워드 선택하러 가기" class="btn btn-primary" id="survey-btn">
</form>

<div class="blank">
</div>


<br>
<%= link_to '다음으로 넘어가기', '/mypouch/keyword' %>