config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'

  # check email uniqueness in js whenever keypress
  post "/check_email" => "home#check_email"

  # mypouch
  get 'mypouch/index' => "mypouch#index"
  get 'mypouch/face'=> "mypouch#face"
  post 'mypouch/survey' => "mypouch#survey"
  get 'mypouch/survey' => "mypouch#survey"
  post 'mypouch/keyword'=> "mypouch#keyword"
  get 'mypouch/keyword'=> "mypouch#face"
  post 'mypouch/result' => "mypouch#result"
  get 'mypouch/result' => "home#index"

  # contents
  resources :contents do
    resources :comments
    member do
      put "like", to: "contents#upvote"
    end
  end
  get "/contents/custom/:category" => "contents#custom"
  get "/contents/filter/:filter" => "contents#filter"

  # products
  resources :products do
    resources :reviews
  end
  get "/products/custom/:category" => "products#custom"
  get "/products/filter/:filter" => "products#filter"

  # ranking
  get '/ranking/category/:category' => "ranking#category"

  # store
  get '/store/index'
  get '/store/category/:category' => "store#category"
  get '/store/filter/:filter' => "store#filter"

  # creatures
  resources :creatures do
    resources :talks
    member do
      put "like", to: "creatures#upvote"
    end
  end
  get 'creatures/category/:category' => "creatures#category"

  # Admin
  get 'admin/index' => "admin#index"
  get 'admin/userinfo' => "admin#userinfo"
  get 'admin/contentinfo' => "admin#contentinfo"
  get 'admin/productinfo' => "admin#productinfo"
  get 'admin/creatureinfo' => "admin#creatureinfo"

  # tinymce
  post '/tinymce_assets' => 'tinymce_assets#create'



end

app/views/admin/contentinfo.html.erb
<table>  
  <tbody>
    <tr>
      <td><p>ID</p></td>
      <td><p>콘텐츠명</p></td>
      <td><p>부제</p></td>
      <td><p>링크</p></td>
      <td><p>카테고리</p></td>
      <td><p>키워드</p></td>
      <td><p>created_at</p></td>
      <td><p>upadted_at</p></td>
      <td><p>작성자</p></td>
      <td><p>관리</p></td>
    </tr>

      <% @contents.each do |content| %>
        <tr>
          <td><%= content.id %></td>
          <td><%= content.title %></td>
          <td><%= content.subtitle %></td>
          <td><%= content.link %></td>
          <td><%= content.category %></td>
          <td><%= content.keyword %></td>
          <td><%= content.created_at %></td>
          <td><%= content.updated_at %></td>
          <td><%= content.user.nickname %></td>
          <td><%= link_to 'Show', content %>
              <%= link_to 'Edit', edit_content_path(content) %>
              <%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr> 
      <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content', new_content_path %>

app/views/admin/creatureinfo.html.erb
<table>  
  <tbody>
    <tr>
      <td><p>ID</p></td>
      <td><p>콘텐츠명</p></td>
      <td><p>부제</p></td>
      <td><p>링크</p></td>
      <td><p>카테고리</p></td>
      <td><p>키워드</p></td>
      <td><p>created_at</p></td>
      <td><p>upadted_at</p></td>
      <td><p>작성자</p></td>
      <td><p>관리</p></td>
    </tr>

      <% @creatures.each do |creature| %>
        <tr>
          <td><%= creature.id %></td>
          <td><%= creature.title %></td>
          <td><%= creature.subtitle %></td>
          <td><%= creature.link %></td>
          <td><%= creature.category %></td>
          <td><%= creature.keyword %></td>
          <td><%= creature.created_at %></td>
          <td><%= creature.updated_at %></td>
          <td><%= creature.user.nickname %></td>
          <td><%= link_to 'Show', creature %>
              <%= link_to 'Edit', edit_content_path(creature) %>
              <%= link_to 'Destroy', creature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr> 
      <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Creature', new_creature_path %>

app/views/admin/index.html.erb
<div>
	<div>
		<h1>등록된 유저 수</h1>
		<p><%= @users.count %>명</p>
		<%= link_to '유저관리', admin_userinfo_path %>
	</div>

	<div>
		<h1>등록된 제품 수</h1>
		<p><%= @products.count %>개</p>
		<%= link_to '제품관리', admin_productinfo_path %>
	</div>	

	<div>
		<h1>등록된 콘텐츠 수</h1>
		<p><%= @contents.count %>개</p>
		<%= link_to '콘텐츠관리', admin_contentinfo_path %>
	</div>

	<div>
		<h1>등록된 크리에이터 콘텐츠 수</h1>
		<p><%= @creatures.count %>개</p>
		<%= link_to '크리에이터 콘텐츠관리', admin_creatureinfo_path %>	
	</div>	
</div>

app/views/admin/productinfo.html.erb
<table>
  <tbody>
    <tr>
      <td><p>ID</p></td>
      <td><p>제품명</p></td>
      <td><p>브랜드</p></td>
      <td><p>가격</p></td>
      <td><p>링크</p></td>
      <td><p>키워드</p></td>
      <td><p>스코어</p></td>   
      <td><p>created_at</p></td>
      <td><p>upadted_at</p></td>
      <td><p>작성자</p></td>
      <td><p>관리</p></td>
    </tr>

      <% @products.each do |product| %>
        <tr>
          <td><%= product.id %></td>          
          <td><%= product.name %></td>
          <td><%= product.brand %></td>
          <td><%= product.price %></td>
          <td><%= product.link %></td>
          <td><%= product.keyword %></td>
          <td><%= product.score %></td>
          <td><%= product.created_at %></td>
          <td><%= product.updated_at %></td>
          <td><%= product.user.nickname %></td>
          <td><%= link_to 'Show', product %>
              <%= link_to 'Edit', edit_product_path(product) %>
              <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr> 
      <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/admin/userinfo.html.erb
<table>  
  <tbody>
    <tr>
      <td><p>ID</p></td>
      <td><p>Email</p></td>
      <td><p>Nickname</p></td>
      <td><p>Phone number</p></td>
      <td><p>Sex</p></td>
      <td><p>Age</p></td>
      <td><p>Skintype</p></td>
      <td><p>Usertype</p></td>
      <td><p>created_at</p></td>
      <td><p>updated_at</p></td>
      <td><p>관리</p></td>
    </tr>

      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.email %></td>
          <td><%= user.nickname %></td>
          <td><%= user.phone%></td>
          <td><%= user.sex %></td>
          <td><%= user.age %></td>
          <td><%= user.skintype %></td>
          <td><%= user.usertype %></td>
          <td><%= user.created_at %></td>
          <td><%= user.updated_at %></td>
          <td></td>
        </tr> 
      <% end %>
  </tbody>
</table>