config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'

  # check email uniqueness in js whenever keypress
  post "/check_email" => "home#check_email"

  # mypouch
  get 'mypouch/index' => "mypouch#index"
  get 'mypouch/face'=> "mypouch#face"
  post 'mypouch/survey' => "mypouch#survey"
  get 'mypouch/survey' => "mypouch#survey"
  post 'mypouch/keyword'=> "mypouch#keyword"
  get 'mypouch/keyword'=> "mypouch#face"
  post 'mypouch/result' => "mypouch#result"
  get 'mypouch/result' => "home#index"

  # contents
  resources :contents do
    resources :comments
    member do
      put "like", to: "contents#upvote"
    end
  end
  get "/contents/custom/:category" => "contents#custom"
  get "/contents/filter/:filter" => "contents#filter"

  # products
  resources :products do
    resources :reviews
  end
  get "/products/custom/:category" => "products#custom"
  get "/products/filter/:filter" => "products#filter"

  # ranking
  get '/ranking/category/:category' => "ranking#category"

  # store
  get '/store/index'
  get '/store/category/:category' => "store#category"
  get '/store/filter/:filter' => "store#filter"

  # creatures
  resources :creatures do
    resources :talks
    member do
      put "like", to: "creatures#upvote"
    end
  end
  get 'creatures/category/:category' => "creatures#category"

  # Admin
  get 'admin/index' => "admin#index"
  get 'admin/userinfo' => "admin#userinfo"
  get 'admin/contentinfo' => "admin#contentinfo"
  get 'admin/productinfo' => "admin#productinfo"
  get 'admin/creatureinfo' => "admin#creatureinfo"

  # tinymce
  post '/tinymce_assets' => 'tinymce_assets#create'



end

app/models/creature.rb
class Creature < ApplicationRecord
  # validation
  validates :title, :presence => true
  validates :subtitle, :presence => true
  validates :body, :presence => true
  validates :category, :presence => true

  belongs_to :user
  has_and_belongs_to_many :tags
  mount_uploader :thumb, ImageUploader
  has_many :talks
  acts_as_votable
  is_impressionable
  resourcify

  after_create do
    creature = Creature.find_by(id: self.id)
    hashtags = self.keyword.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      creature.tags << tag
    end
  end

  before_update do
    creature = Creature.find_by(id: self.id)
    creature.tags.clear
    hashtags = self.keyword.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      creature.tags << tag
    end
  end
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  before_action :set_creature, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :delete, :upvote]
  impressionist actions: [:show]

  # GET /creatures
  # GET /creatures.json
  def index
    @creatures = Creature.all
  end

  # GET /creatures/1
  # GET /creatures/1.json
  def show
    @tags = @creature.tags
  end

  # GET /creatures/new
  def new
    @creature = current_user.creatures.build
  end

  # GET /creatures/1/edit
  def edit
  end

  # POST /creatures
  # POST /creatures.json
  def create
    @creature = current_user.creatures.build(creature_params)

    respond_to do |format|
      if @creature.save
        format.html { redirect_to @creature, notice: 'Creature was successfully created.' }
        format.json { render :show, status: :created, location: @creature }
      else
        format.html { render :new }
        format.json { render json: @creature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creatures/1
  # PATCH/PUT /creatures/1.json
  def update
    respond_to do |format|
      if @creature.update(creature_params)
        format.html { redirect_to @creature, notice: 'Creature was successfully updated.' }
        format.json { render :show, status: :ok, location: @creature }
      else
        format.html { render :edit }
        format.json { render json: @creature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creatures/1
  # DELETE /creatures/1.json
  def destroy
    @creature.destroy
    respond_to do |format|
      format.html { redirect_to creatures_url, notice: 'Creature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def category
    @category = params[:category]
    if @category == "all"
      @creatures = Creature.all
    else
      if @category == "skincare"
        @cate_ko = "스킨케어"
      elsif @category == "faceup"
        @cate_ko = "페이스업"
      elsif @category == "hair"
        @cate_ko = "헤어"
      else
        @cate_ko = "바디"
      end
      @creatures = Creature.where(:category => @cate_ko)
    end
  end

  def upvote
    @creature = Creature.find(params[:id])

    @creature.upvote_by current_user
    redirect_to(request.referer)
    # redirect_to(request.referrer, :notice => '해당 글을 추천하셨습니다.')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creature
      @creature = Creature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def creature_params
      params.require(:creature).permit(:thumb, :title, :subtitle, :body, :link, :category, :keyword,
                                      :normal, :dry, :oily, :complex, :sensitive,
                                      :notcare, :basecare, :hardcare, :makeup, :idol)
    end
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/views/creatures/_form.html.erb
<%= form_for(creature) do |f| %>
  <% if creature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(creature.errors.count, "error") %> prohibited this creature from being saved:</h2>

      <ul>
      <% creature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :thumb %>
    <%= f.file_field :thumb, accept: 'image/png image/gif image/jpg' %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= tinymce :language => "ko" %>
    <%= f.text_area :body, id: :content_body, class: "form-control tinymce", rows: "10" %>

  </div>
  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :category %>
    <%= f.select(:category, ['스킨케어', '페이스업', '헤어', '바디'] , {}, { :class => ''}) %>
  </div>
  <div class="field">
    <%= f.label :keyword %>
    <%= f.text_field :keyword %>
  </div>

  <div class="field">
    <%= f.label :normal %>
    <%= f.radio_button :normal, true %>
    <%= f.label :normal, 'yes' %>
    <%= f.radio_button :normal, false %>
    <%= f.label :normal, 'no' %>
  </div>
  <div class="field">
    <%= f.label :dry %>
    <%= f.radio_button :dry, true %>
    <%= f.label :dry, 'yes' %>
    <%= f.radio_button :dry, false %>
    <%= f.label :dry, 'no' %>
  </div>
  <div class="field">
    <%= f.label :oily %>
    <%= f.radio_button :oily, true %>
    <%= f.label :oily, 'yes' %>
    <%= f.radio_button :oily, false %>
    <%= f.label :oily, 'no' %>
  </div>
  <div class="field">
    <%= f.label :complex %>
    <%= f.radio_button :complex, true %>
    <%= f.label :complex, 'yes' %>
    <%= f.radio_button :complex, false %>
    <%= f.label :complex, 'no' %>
  </div>
  <div class="field">
    <%= f.label :sensitive%>
    <%= f.radio_button :sensitive, true %>
    <%= f.label :sensitive, 'yes' %>
    <%= f.radio_button :sensitive, false %>
    <%= f.label :sensitive, 'no' %>
  </div>

  <div class="field">
    <%= f.label :notcare %>
    <%= f.radio_button :notcare, true %>
    <%= f.label :notcare, 'yes' %>
    <%= f.radio_button :notcare, false %>
    <%= f.label :notcare, 'no' %>
  </div>
  <div class="field">
    <%= f.label :basecare %>
    <%= f.radio_button :basecare, true %>
    <%= f.label :basecare, 'yes' %>
    <%= f.radio_button :basecare, false %>
    <%= f.label :basecare, 'no' %>
  </div>
  <div class="field">
    <%= f.label :hardcare %>
    <%= f.radio_button :hardcare, true %>
    <%= f.label :hardcare, 'yes' %>
    <%= f.radio_button :hardcare, false %>
    <%= f.label :hardcare, 'no' %>
  </div>
  <div class="fielhardcared">
    <%= f.label :makeup %>
    <%= f.radio_button :makeup, true %>
    <%= f.label :makeup, 'yes' %>
    <%= f.radio_button :makeup, false %>
    <%= f.label :makeup, 'no' %>
  </div>
  <div class="field">
    <%= f.label :idol %>
    <%= f.radio_button :idol, true %>
    <%= f.label :idol, 'yes' %>
    <%= f.radio_button :idol, false %>
    <%= f.label :idol, 'no' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/creatures/category.html.erb
<nav class="m_sub_title">
  <ul>
    <li><a class="m_m1" href="/creatures/category/<%= 'all' %>">ALL</a></li>
    <li><a class="m_m2" href="/creatures/category/<%= 'skincare' %>">스킨케어</a></li>
    <li><a class="m_m3" href="/creatures/category/<%= 'faceup' %>">페이스업</a></li>
    <li><a class="m_m4" href="/creatures/category/<%= 'hair' %>">헤어</a></li>
    <li><a class="m_m5" href="/creatures/category/<%= 'body' %>">바디</a></li>
  </ul>
</nav>
<nav class="m_sub_title_blank"></nav>

<article>
  <% @creatures.each do |creature| %>
    <div class="" style="border: 1px solid #555">
      <div class="">
        <%= link_to image_tag(creature.thumb.main), creature_path(creature) %><!-- 썸네일 이미지 -->
      </div>

      <div class="">
        <h3><span style="color:red;"><%= creature.category%></span> | <%= creature.title %></h3><!-- 타이틀이 노출됩니다. -->
      </div>

      <div class>
        <%= link_to "Likes #{creature.get_upvotes.size}", like_creature_path(creature), method: :put %>
        <span>Views <%= creature.impressionist_count %></span>
      </div>

      <div class="">
        <p>
          <% tags = creature.tags %>
          <% tags.each do |tag| %><!--키워드 전체가 노출됩니. -->
            <span>#<%= tag.name %></span>&nbsp
          <% end %>
        </p>
      </div>
    </div>
  <% end %>

  <%= link_to 'New Creature', new_creature_path %>
</article>

app/views/creatures/edit.html.erb
<h1>Editing Creature</h1>

<%= render 'form', creature: @creature %>

<%= link_to 'Show', @creature %> |
<%= link_to 'Back', creatures_path %>

app/views/creatures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Creatures</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @creatures.each do |creature| %>
      <tr>
        <td><%= link_to 'Show', creature %></td>
        <td><%= link_to 'Edit', edit_creature_path(creature) %></td>
        <td><%= link_to 'Destroy', creature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Creature', new_creature_path %>

app/views/creatures/new.html.erb
<h1>New Creature</h1>

<%= render 'form', creature: @creature %>

<%= link_to 'Back', creatures_path %>

app/views/creatures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h3>Thumbnail</h3>
  <img src="<%= @creature.thumb.detail %>" alt="" />
</p>
<h3>Title: <%= @creature.title %></h3>
<p>Subtitle: <%= @creature.subtitle %></p>

<article class="" style="border: 1px solid #555">
  <h3>Body</h3>
  <p>
    <%= @creature.body.html_safe%>
  </p>
  <p>
    <%= link_to "Likes #{@creature.get_upvotes.size}", like_creature_path(@creature), method: :put %>
    <span>Views <%= @creature.impressionist_count %></span>
  </p>
</article>

<p>
  <h3>태그</h3>
  <% @tags.each do |tag| %>
    <span>#<%= tag.name %></span>&nbsp
  <% end %>
</p>

<%= link_to 'Edit', edit_creature_path(@creature) %> |
<%= link_to 'Destroy', @creature, method: :delete, data: { confirm: 'Are you sure?' } %>

<hr>

<div class="">
  <h3><%= @creature.talks.count %> Talks</h3>
  <%= render @creature.talks %>
  <h3>Add a Talk: </h3>
  <%= render "talks/form" %>
</div>